### ISSUE TITLE
As a user, I want the SIP manifest to include valid URLs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#102]
...so that I can ensure the validity of the SIP

---

**Acceptance Criteria**
TBD

---

**Engineering Tasks**
- [x] provide spot check of bundle.xml URL to make sure the URL is valid

**Comment by jordanpadams** [comment]
@nutjob4life since you are working on the other deep-archive ticket right now, does this seem like something that is pretty simple? basically, we just want to ping the `base_url + bundle path` that would go in the SIP to make sure it is valid. we can assume everything else in the SIP is valid for the time being.

**Comment by nutjob4life** [comment]
@jordanpadams are you thinking going beyond just `if urlparse(url) succeeds` but also `urlopen(url) and get some valid data`?

**Comment by jordanpadams** [comment]
@nutjob4life just `urlparse(url) success`. very simple to make sure the path exists. we can provide some more robust validation of URLs using the registry through some other component.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can you quickly add the acceptance criteria that Gary will use for I&T ? Thanks

**Comment by jordanpadams** [comment]
@tloubrieu-jpl done
