### ISSUE TITLE
Improvements per API updates to remove workarounds from code

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#106]
Once these blocker(s) have been completed and deployed, update pds-deep-archive to no longer include workaround flags. The blocking issue(s) are as follows:

- [x] https://github.com/NASA-PDS/registry-api-service/issues/17 🤔, we shouldn't work around bad documents
- [x] https://github.com/NASA-PDS/registry-api-service/issues/49 😬

**Comment by jordanpadams** [comment]
@nutjob4life can you add those blockers to this ticket?

**Comment by nutjob4life** [comment]
@jordanpadams added to the ticket description 👍

**Comment by nutjob4life** [comment]
Still blocked by https://github.com/NASA-PDS/registry-api-service/issues/17 but reading the discussion there is like totally 🤯
