### ISSUE TITLE
Update PDS Deep "Registry" Archive and remove workaround + implement latest-only-feature per API updates

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-deep-archive#107]
These aren't blockers like #106 but should be addressed so we can remove the "workaround" command-line arguments:

- [ ] https://github.com/NASA-PDS/pds-api/issues/74 🧐, server-side support for latest collection on LID-only bundle members a must-have
- [ ] https://github.com/NASA-PDS/pds-api/issues/73 😌, nice to have but less serious

Once the corresponding API improvements are made, the workarounds may be removed and we can call this done.

## Engineering Details
- [ ] remove `--disable-pagination-workaround` flag and functionality
- [ ] ~~remove~~ support `--include-latest-collection-only` flag and develop functionality to support this

(EDIT: changed "remove" to "support"; we don't want to remove the flag. We want to make it work.)

**Comment by jordanpadams** [comment]
@nutjob4life we unfortunately do not have this functionality deployed somewhere... BUT the capabilities have been ingested. could we maybe try this with by deploying a local instance of the registry? https://github.com/NASA-PDS/pds-registry-app#run

**Comment by nutjob4life** [comment]
Thanks @jordanpadams. The instructions you linked are much better than the ones at https://github.com/NASA-PDS/registry-api-service

Currently stuck on `[ERROR] Could not find datatype for field 'cart:Polar_Stereographic/cart:straight_vertical_longitude_from_pole'` but reading up on registry customization 👍

**Comment by nutjob4life** [comment]
FYI @jordanpadams  `--include-latest-collection-only` isn't a workaround. It's a feature! We don't want to remove it; we want to **support** it the way we do for on-disk bundles.

(I mean, I can remove it—that'd be even easier.)
