### ISSUE TITLE
deep archive misses products that specify primary products using lower case 'p'

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#116]
## 🐛 Describe the bug

The SIP/transfer/checksum manifest files in a Deep Archive package do not list a primary basic product designated by lowercase “p” in the collection inventory file.  The Standards do not appear to restrict the membership value to uppercase “P” or “S” in a collection inventory file.

## 📜 To Reproduce
Run `pds-deep-archive` against a collection specifying a primary product with `P` instead of `p`

## 🕵️ Expected behavior

`pds-deep-archive` should be case agnostic when it comes to specifying primary/secondary products.

---

**Comment by nutjob4life** [comment]
The code for "p-lines" currently is:

```python
_pLineMatcher = re.compile(r'^P,\s*([^\s]+)::([^\s]+)')
```

So it _currently_ matchies capital `P`. I think the issue title and "to reproduce" are flipped.

I'll add a test case that includes mixed case `P`/`p` to test in case (see what I did there 😏) case-insensitivity is working.
