### ISSUE TITLE
AIP Generator not outputting correctly for spice example bundle

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/pds-deep-archive#41]
### Describe the bug

Run `pds-deep-archive` or `aipgen` (either command) as follows:
```
$ bin/pds-deep-archive --site PDS_NAI --offline --bundle-base-url https://naif.jpl.nasa.gov/pub/naif/pds/pds4/insight/ insight_spice/bundle_insight_spice_v001.xml 
$ bin/aipgen insight_spice/bundle_insight_spice_v001.xml
```
This results in the checksum manifest and transfer manifest containing *all* versions of the collection, but should only contain those referenced from `bundle_insight_spice_v001.xml`

### Test Data / Additional context

See #39 for related issues with the spice example bundle.

**Comment by jordanpadams** [comment]
@nutjob4life one other issue I found with the AIP generation was the filenames:

e.g. for insight.spice_v2.0:
```
LID = urn:nasa:pds:system_bundle:product_aip:insight.spice_v2.0
VID = 1.0
```
but filename outputs as
```
insight.spice_v2.0_aip_v2.0.xml
```
but it should be:
```
insight.spice_v2.0_aip_v1.0.xml
```
