### ISSUE TITLE
Update Usage instructions to more clearly define command-line arguments

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds-deep-archive#59]
Below, I replaced the prompt "[pds-deep-archive] /Users/rchen>" with "%" for clarity. I'm running tcsh

/Users/rchen> source $HOME/.virtualenvs/pds-deep-archive/bin/activate.csh
% pds-deep-archive --version
pds-deep-archive 0.1.0
% pds-deep-archive -s PDS_ATM -b https://atmos.nmsu.edu/PDS/data/PDS4/LADEE test/data/ladee_test/mission_bundle/LADEE_Bundle_1101.xml
usage: pds-deep-archive [-h] [--version] -s
                        {PDS_ATM,PDS_ENG,PDS_GEO,PDS_IMG,PDS_JPL,PDS_NAI,PDS_PPI,PDS_PSI,PDS_RNG,PDS_SBN}
                        [-n] -b BUNDLE_BASE_URL [-i] [-d | -q]
                        IN-BUNDLE.XML
pds-deep-archive: error: argument IN-BUNDLE.XML: can't open 'test/data/ladee_test/mission_bundle/LADEE_Bundle_1101.xml': [Errno 2] No such file or directory: 'test/data/ladee_test/mission_bundle/LADEE_Bundle_1101.xml'

[ATMOS seemingly reorganized their directory, but what I think is correct doesn't work either]

% curl https://atmos.nmsu.edu/PDS/data/PDS4/LADEE/mission_bundle/LADEE_Bundle_1101.xml
[I'm manually replacing lessthans with the ampersand equivalent]
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;?xml-model href="http://pds.nasa.gov/pds4/schema/released/pds/v1/PDS4_PDS_1101.sch" ?&gt;
[snip...]
% pds-deep-archive -s PDS_ATM -b https://atmos.nmsu.edu/PDS/data/PDS4/LADEE mission_bundle/LADEE_Bundle_1101.xml       
usage: pds-deep-archive [-h] [--version] -s
                        {PDS_ATM,PDS_ENG,PDS_GEO,PDS_IMG,PDS_JPL,PDS_NAI,PDS_PPI,PDS_PSI,PDS_RNG,PDS_SBN}
                        [-n] -b BUNDLE_BASE_URL [-i] [-d | -q]
                        IN-BUNDLE.XML
pds-deep-archive: error: argument IN-BUNDLE.XML: can't open 'mission_bundle/LADEE_Bundle_1101.xml': [Errno 2] No such file or directory: 'mission_bundle/LADEE_Bundle_1101.xml'

**Comment by jordanpadams** [comment]
@rchenatjpl apologies this wasn't clear. will update the docs per this ticket. for the sake of ensuring your testing can move along, the test was intended to just show an example, but the you need to download a bundle, and then run it against that bundle on your local file system (or in the discipline node case they would run this on the file system with the data).

So the IN-BUNDLE.XML should be more clear that should be a file on your file-system, and all that data should be where you are running the software.

1. Download the mission bundle
2. Run the software:
```
pds-deep-archive -s PDS_ATM -b https://atmos.nmsu.edu/PDS/data/PDS4/LADEE    \
                              /path/to/ladee/mission_bundle/LADEE_Bundle_1101.xml
```

**Comment by jordanpadams** [comment]
i also see from the docs that software execution command is too long so you can't see that there is a file path needed at the end there.
