### ISSUE TITLE
Software appears to be excluding all the products associated with the collections

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#69]
**Describe the bug**
When running deep archive on this EPOXI bundle (`pds-gamma:/data/local/starbase/data/pds4/test-bundles/pds4-epoxi_mri-v1.0`) all the data files under `hartley2_photometry/data/` are missing.

**To Reproduce**
1. Download the data from above
2. Run `pds-deep-archive -s PDS_SBN -b https://pdssbn.astro.umd.edu/holdings/ pds4-epoxi_mri-v1.0/bundle.xml`

**Expected behavior**
the SIP and AIP should contain all the product references in `pds4-epoxi_mri-v1.0/hartley2_photometry/inventory.csv`

Note some of the weirdness with this bundle:
* There is an `overview.xml` in the same directory as `collection.xml` so we need to make sure that file is included.
* There are `data` and `document` sub-directories that both contain data from the `inventory.csv` (this is horrendous archiving, but it is what it is)
* `pds4-epoxi_mri-v1.0/hartley2_photometry/document/epoxi_photometry_v5.[xml|pdf]` should actually not be included in the SIP/AIP because its LID does not match the LID in the inventory file

Refs #32

**Comment by jordanpadams** [comment]
Update: It appears the software is only outputting bundles/collections and not any of the associated products. It appears all the files are getting written to the database, just not the AIP/SIP.

**Comment by nutjob4life** [comment]
Note to self (i.e., @nutjob4life): we parse for "P" lines in any `<file_name>` so long as the root element is a `<Product_Collection>`. We don't have to key off of `.tab` files like we currently are doing.
