### ISSUE TITLE
As a user, I want to generate AIPs and SIPs using Registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#7]

**Comment by tloubrieu-jpl** [comment]
@nutjob4life will work on the new version of the registry and API, but the tool still need to work if the data is not available in this new registry/api since they will not be fully deployed/initialized too soon.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life :
The validation api end point is available on https://pds-gamma.jpl.nasa.gov/api/swagger-ui.html

The python API client is on https://github.com/NASA-PDS/pds-api-client

**Comment by tloubrieu-jpl** [comment]
@nutjob4life was not able to make the python api client work. @tloubrieu-jpl need to look.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life is finalizing the on-going refactoring.

We'll discuss a better integration of demo client/server next Thursday.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life I have updated the pds-gamma api service and it now works with the api client, see https://github.com/NASA-PDS/pds-api-notebook/tree/main

Let me know if you have questions on that.

**Comment by nutjob4life** [comment]
Confirmed! I can successfully use `pds.api_client` with `https://pds-gamma.jpl.nasa.gov/api/`. Thanks!

**Comment by jordanpadams** [comment]
@nutjob4life i prefer option `pds-deep-archive --registry https://pds-gamma.jpl.nasa.gov/api/  urn:nasa:pds:insight_documents::2.0` . This seems the simplest for the user, and they shouldn't have to care/know the REST API query for their product (also in case the API changes).
