### ISSUE TITLE
Output SIP uses backslash in output URLs on Windows

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-deep-archive#82]
**Describe the bug**
Output in SIP:
```
e5a8de222f6347070867d6d0b83f0025	MD5	https://sbnarchive.psi.edu/pds4/orex\orex.mission\bundle_mission.xml	urn:nasa:pds:orex.mission::7.0
```

**To Reproduce**
<img width="1277" alt="Screen Shot 2020-10-08 at 6 16 14 AM" src="https://user-images.githubusercontent.com/33492486/95463590-c8aea880-092d-11eb-8caa-40fef5ecf4c9.png">

**Expected behavior**

** Version of Software Used**
Output from `validate -V`

**Desktop (please complete the following information):**
<img width="752" alt="Screen Shot 2020-10-08 at 6 17 07 AM" src="https://user-images.githubusercontent.com/33492486/95463676-e67c0d80-092d-11eb-969d-c4225cf135ba.png">
- pds.deeparchive 0.2.0

**Comment by nutjob4life** [comment]
😮

**Comment by nutjob4life** [comment]
Hi @jordanpadams! it looks like there are backslashes in the AIP files too:

![Screen Shot 2020-10-08 at 7 34 36 PM](https://user-images.githubusercontent.com/814813/95528307-57a6d980-099d-11eb-98c4-a2511e4a429a.png)

But as I recall from an [early design example](https://github.com/NASA-PDS/pds-deep-archive/issues/3), that was _supposed_ to be the case. Then [this commit](https://github.com/NASA-PDS/pds-deep-archive/commit/43d0f66ca6d0223fe65fe26bcaf568db9b4d8492#diff-d80b3afe177ff226dbebc9786cf024a3) commented-out the backslashes (with the added "injury" of commenting-out code without a comment explaining why 😂).

So—while I'm in here—should AIPs be forward slashes as well? 🤔

**Comment by jordanpadams** [comment]
@nutjob4life i remember that too, but let's fix both? windows can mostly support '/' but unix totally freaks out at backslash
