### ISSUE TITLE
Try to create a package

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-deep-archive#87]
**Describe the bug**
Error when using command

**To Reproduce**
With same input file:
[bundle.xml.zip](https://github.com/NASA-PDS/pds-deep-archive/files/5475566/bundle.xml.zip)

**Gary I&T test:**
$ pds-deep-archive -s PDS_RNG -b https://rings.edu/PDS/data/PDS4/ testDeep/uranus_occ_support/bundle.xml 
INFO 👟 PDS Deep Archive, version 0.2.2
Traceback (most recent call last):
  File "/home/gxchen/.virtualenvs/pds-deep-archive/bin/pds-deep-archive", line 11, in <module>
    load_entry_point('pds.deeparchive==0.2.2', 'console_scripts', 'pds-deep-archive')()
  File "/home/gxchen/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/main.py", line 102, in main
    comprehendDirectory(os.path.dirname(os.path.abspath(args.bundle.name)), con)
  File "/home/gxchen/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/utils.py", line 124, in comprehendDirectory
    tree = parseXML(xmlFile)
  File "/home/gxchen/.virtualenvs/pds-deep-archive/lib64/python3.6/site-packages/pds/aipgen/utils.py", line 181, in parseXML
    return etree.parse(f)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/gxchen/pds-test/PDS4test.build10b/testDeep/uranus_occ_support/._bundle.xml", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

**Thomas attempt to reproduce**

 %  pds-deep-archive -s PDS_RNG -b https://rings.edu/PDS/data/PDS4/ ~/Downloads/bundle.xml  
INFO 👟 PDS Deep Archive, version 0.2.2
WARNING ⚠️ File SystemSpecificationV1.0.pdf referenced by /Users/loubrieu/Downloads/SystemSpecificationV1.0.xml does not exist; ignoring
WARNING ⚠️ File DataAdministrationPlan-1990 referenced by /Users/loubrieu/Downloads/DataAdministrationPlan-1990.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/bundle.xml does not exist; ignoring
WARNING ⚠️ File SystemDeliveryReview-1990.pdf referenced by /Users/loubrieu/Downloads/SystemDeliveryReview-1990.xml does not exist; ignoring
WARNING ⚠️ File SPIDSv1.1-1988.pdf referenced by /Users/loubrieu/Downloads/SPIDSv1.1-1988.xml does not exist; ignoring
WARNING ⚠️ File SystemRequirementsReview-1986.pdf referenced by /Users/loubrieu/Downloads/SystemRequirementsReview-1986.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a16lsm_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a17fuvs_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15hfe_calibrated_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15hfe_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15photosupportdata_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a17lsg_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File README.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15_17_hfe_concatenated_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a12sws_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a17photosupportdata_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15side_ccig_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a17hfe_calibrated_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a15oms_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a17hfe_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a16oms_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/pioneer89cdd_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a16_photosupportdata_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/a12side_ccig_raw_arcsav_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/apollodoc_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_Apollo_Bundles_reserve_20200316/aaaSubmitted_by_GEO_active_20200330/apollo_bundles/pioneerdoc_bundle.xml does not exist; ignoring
WARNING ⚠️ File readme.txt referenced by /Users/loubrieu/Downloads/aaDOI_production_submitted_labels[4]/GEO_reserve_shocked_feldspar_20200330/aaaSubmitted_by_GEO_20200316/bundle_lab_shocked_feldspars.xml does not exist; ignoring
Traceback (most recent call last):
  File "/Users/loubrieu/tmp/venv-d/bin/pds-deep-archive", line 11, in <module>
    load_entry_point('pds.deeparchive==0.2.2', 'console_scripts', 'pds-deep-archive')()
  File "/Users/loubrieu/tmp/venv-d/lib/python3.7/site-packages/pds/aipgen/main.py", line 102, in main
    comprehendDirectory(os.path.dirname(os.path.abspath(args.bundle.name)), con)
  File "/Users/loubrieu/tmp/venv-d/lib/python3.7/site-packages/pds/aipgen/utils.py", line 126, in comprehendDirectory
    lid, vid = getLogicalVersionIdentifier(tree)
  File "/Users/loubrieu/tmp/venv-d/lib/python3.7/site-packages/pds/aipgen/utils.py", line 94, in getLogicalVersionIdentifier
    lid = matches[0].text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
(venv-d) (base) loubrieu@MT-212318 tmp % python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pds.deeparchive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pds.deeparchive'
>>> import pds-deep-archive
  File "<stdin>", line 1
    import pds-deep-archive
              ^
SyntaxError: invalid syntax
>>> import pds_deep_archive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pds_deep_archive'
>>> 
(venv-d) (base) loubrieu@MT-212318 tmp % pip freeze 
lxml==4.6.1
pds.deeparchive==0.2.2

** Version of Software Used**
0.2.2

**Desktop (please complete the following information):**
 Gary: ?
- Thomas: MacOS

**Comment by nutjob4life** [comment]
@tloubrieu-jpl I don't think this is a bug so much as the presence of a zero-length `.xml` file under Gary's `testDeep/uranus_occ_support/` directory but I can treat it as a bug if you like.

However I will need access to the entire `testDeep/uranus_occ_support` and not just the `bundle.xml.zip` attached to this issue.

**Comment by tloubrieu-jpl** [comment]
Thanks @nutjob4life I will report to Gary.
