### ISSUE TITLE
Small typo on package documentation

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/pds-deep-archive#90]
Small typo in the documentation. 
The documentation describes the following argument: 
 --include-latest-collections-only
whereas it should be
 --include-latest-collection-only

**To Reproduce**
Go to: https://nasa-pds.github.io/pds-deep-archive/usage/index.html#usage-information

**Comment by jordanpadams** [comment]
nice catch @mcostasitja ! Fixed.  Will be out in a future release.
