### ISSUE TITLE
SIP manifest table erroneously includes secondary collections and their basic products

### ISSUE THREAD

**Issue by smclaughlin7** [NASA-PDS/pds-deep-archive#92]
Bug: The software is erroneously including secondary collections and their basic products in the manifest table of SIP product (Product_SIP_Deep_Archive) that is submitted to the NSSDCA.

Details: NAIF recently submitted a bunch of SIPs where a document collection with secondary membership in the bundle is included in the manifest table, e.g., the InSight v2.0 SIP at https://pds.nasa.gov/data/pds4/manifests/insight.spice_v2.0_20201218_sip_v1.0.xml.  (The basic products in the “secondary” collection have primary membership, which actually makes sense; they’re included in the manifest as well.)

Expected Action: The Deep Archive software is not supposed to include collections and basic products with secondary membership in the SIP manifest table. This also applies to all basic products, irregardless of membership, of a collection with secondary membership in a bundle.

**Comment by nutjob4life** [comment]
Not sure how a "secondary" collection is indicated in the bundle.xml, .tab files, etc.; but I'm sure I'll figure it out 😉

**Comment by jordanpadams** [comment]
@nutjob4life see https://naif.jpl.nasa.gov/pub/naif/pds/pds4/insight/insight_spice/bundle_insight_spice_v002.xml .

```
  <Bundle_Member_Entry>
    <lidvid_reference>urn:nasa:pds:insight.spice:spice_kernels::2.0</lidvid_reference>
    <member_status>Primary</member_status>
    <reference_type>bundle_has_spice_kernel_collection</reference_type>
  </Bundle_Member_Entry>
  <Bundle_Member_Entry>
    <lidvid_reference>urn:nasa:pds:insight.spice:document::1.0</lidvid_reference>
    <member_status>Secondary</member_status>
    <reference_type>bundle_has_document_collection</reference_type>
  </Bundle_Member_Entry>
```

**Comment by nutjob4life** [comment]
FYI @jordanpadams if there's no `<member_status>` I'm planning on treating that as "not primary"

**Comment by jordanpadams** [comment]
@nutjob4life if there is no `member_status`, that is a fatal error because that means the bundle is invalid.

**Comment by nutjob4life** [comment]
Okay @jordanpadams raising an exception instead
